[package]
name = "backup"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "backup"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }

backup_integrity = { workspace = true } 
