[package]
name = "backup"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "backup"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
bip0039 = "0.10.1"
magic-crypt = "3.1.12"
sha2 = "0.10"


backup_integrity = { workspace = true } 
